const testData = [
  { 
    id: 'T1', 
    title: 'BIOLOGY MDCAT', 
    subject: 'Biology', 
    chapter: '1. ACELLULAR LIFE', 
    exam: 'MDCAT', 
    province: 'All Provinces', 
    mcqs: [
        { q: "What did Dmitri Ivanovsky's filtration experiments with Tobacco Mosaic Disease sap demonstrate?", options: ["Bacteria cause the disease.", "The infectious agent could pass through filters that retain bacteria.", "Viruses contain DNA.", "The infectious agent could be crystallized."], answer: 1 },
        { q: "The term 'virus' originates from a Latin word meaning:", options: ["Small particle", "Poison", "Filterable agent", "Living fluid"], answer: 1 },
        { q: "Which of the following is NOT a characteristic used to argue that viruses are non-living?", options: ["Ability to replicate only inside host cells", "Lack of metabolic machinery", "Possession of genetic material", "Ability to be crystallized."], answer: 2 },
        { q: "Which scientist first crystallized a virus (TMV), demonstrating it could behave like a chemical?", options: ["Charles Chamberland", "Martinus Beijerinck", "Wendell Stanley", "Louis Pasteur"], answer: 2 },
        { q: "Viruses are considered obligate intracellular parasites because they:", options: ["Can survive outside host cells indefinitely", "Lack ribosomes and energy-generating systems", "Always kill their host cells", "Have DNA genomes"], answer: 1 },
        { q: "Which of the following is a unique property of viral genomes compared to cellular organisms?", options: ["They can be single-stranded DNA", "They can be double-stranded RNA", "They can be segmented", "All of the above"], answer: 3 },
        { q: "The primary reason viruses are not classified in the traditional biological taxonomy (e.g., Kingdom, Phylum) is:", options: ["They are too small", "They lack cellular structure", "They do not evolve", "They are considered chemicals"], answer: 1 },
        { q: "Which statement about viral host range is correct?", options: ["All viruses can infect any type of cell", "Host range is determined by the presence of specific host receptors", "Plant viruses commonly infect humans", "Bacteriophages can infect animal cells"], answer: 1 },
        { q: "The 'virocell' concept refers to:", options: ["A virus particle outside a host", "A host cell that has been converted into a virus-producing factory", "A type of viroid", "A giant virus with cellular genes"], answer: 1 },
        { q: "Which of the following is evidence supporting the origin of viruses from cellular organisms?", options: ["Presence of reverse transcriptase", "Genetic similarity between viral and host genes", "Ability to form crystals", "Lack of envelopes"], answer: 1 },
        { q: "The primary function of the viral capsid is to:", options: ["Carry out metabolic reactions", "Protect the viral genome", "Attach to host cells", "Synthesize viral proteins"], answer: 1 },
        { q: "Which symmetry is found in the capsid of Adenovirus?", options: ["Helical", "Icosahedral", "Complex", "Amorphous"], answer: 1 },
        { q: "Viral envelopes are typically acquired from:", options: ["The environment", "Host cell membranes during budding", "Self-synthesized lipids", "Other viruses"], answer: 1 },
        { q: "Glycoprotein spikes on enveloped viruses are crucial for:", options: ["Genome replication", "Host cell recognition and attachment", "Capsid assembly", "Energy production"], answer: 1 },
        { q: "The nucleocapsid refers to:", options: ["The viral envelope", "The capsid + viral genome", "Viral RNA only", "Host cell nucleus infected by virus"], answer: 1 },
        { q: "Which component is present in ALL viruses?", options: ["Lipid envelope", "DNA genome", "Protein capsid", "Glycoprotein spikes"], answer: 2 },
        { q: "Non-enveloped viruses are generally more resistant to:", options: ["Freezing", "Detergents and solvents", "UV light", "All of the above"], answer: 1 },
        { q: "The triangulation number (T-number) in icosahedral viruses determines:", options: ["Genome size", "Number of capsomeres", "Type of nucleic acid", "Host range"], answer: 1 },
        { q: "Which of the following viruses has a helical capsid?", options: ["Adenovirus", "Tobacco Mosaic Virus", "HIV", "Herpesvirus"], answer: 1 },
        { q: "Viral tegument is a feature of:", options: ["Bacteriophages", "Herpesviruses", "Picornaviruses", "Retroviruses"], answer: 1 },
        { q: "The Baltimore classification system categorizes viruses based on:", options: ["Host range", "Capsid symmetry", "Genome type and replication strategy", "Disease severity"], answer: 2 },
        { q: "Which Baltimore group includes retroviruses like HIV?", options: ["Group IV", "Group V", "Group VI", "Group VII"], answer: 2 },
        { q: "A positive-sense single-stranded RNA virus genome can directly function as:", options: ["Template for DNA synthesis", "mRNA for protein translation", "Substrate for reverse transcriptase", "Integrase target"], answer: 1 },
        { q: "Which virus has a partially double-stranded DNA genome with an RNA intermediate?", options: ["Hepatitis A virus", "Hepatitis B virus", "Hepatitis C virus", "HIV"], answer: 1 },
        { q: "Segmented genomes are characteristic of:", options: ["HIV", "Influenza virus", "Hepatitis B virus", "Adenovirus"], answer: 1 },
        { q: "Which enzyme is carried within the virion of negative-sense RNA viruses?", options: ["DNA polymerase", "Reverse transcriptase", "RNA-dependent RNA polymerase", "Integrase"], answer: 2 },
        { q: "Viroids differ from viruses in that viroids:", options: ["Have a protein coat", "Infect animals", "Consist only of circular RNA", "Have a DNA genome"], answer: 2 },
        { q: "Prions are unique because they lack:", options: ["Protein", "Nucleic acid", "Infectivity", "Ability to cause disease"], answer: 1 },
        { q: "Satellite viruses require a helper virus for:", options: ["Replication", "Capsid formation", "Host attachment", "All of the above"], answer: 3 },
        { q: "Which is a DNA virus?", options: ["Influenza virus", "HIV", "Herpes simplex virus", "Dengue virus"], answer: 2 },
        { q: "The first step in the viral replication cycle is:", options: ["Penetration", "Attachment", "Uncoating", "Replication"], answer: 1 },
        { q: "In bacteriophage T4, the tail fibers are involved in:", options: ["DNA injection", "Host cell recognition", "Capsid assembly", "Genome replication"], answer: 1 },
        { q: "The 'eclipse phase' in viral replication refers to the period when:", options: ["Virions are assembling", "No infectious virions are detectable inside the host cell", "Host cell lysis occurs", "Viral DNA integrates into host genome"], answer: 1 },
        { q: "Lysogenic conversion occurs when:", options: ["The host cell is immediately lysed", "Viral DNA integrates into the host genome", "The virus exists as a prophage", "Both B and C"], answer: 3 },
        { q: "Reverse transcriptase is an enzyme that synthesizes:", options: ["RNA from DNA", "DNA from RNA", "Protein from RNA", "RNA from protein"], answer: 1 },
        { q: "HIV protease is essential for:", options: ["Viral entry", "Cleaving viral polyproteins into functional units", "Reverse transcription", "Integration"], answer: 1 },
        { q: "The enzyme integrase in HIV is responsible for:", options: ["Viral budding", "Inserting viral DNA into host chromosome", "Cleaving viral proteins", "Converting RNA to DNA"], answer: 1 },
        { q: "Which cycle results in immediate host cell lysis?", options: ["Lysogenic cycle", "Lytic cycle", "Latent cycle", "Chronic cycle"], answer: 1 },
        { q: "In the lytic cycle of bacteriophage, the stage where viral components are assembled into new virions is called:", options: ["Penetration", "Biosynthesis", "Maturation", "Release"], answer: 2 },
        { q: "Viral budding typically occurs in:", options: ["Naked viruses", "Enveloped viruses", "Bacteriophages", "Viroids"], answer: 1 },
        { q: "Interferons are host proteins that:", options: ["Directly destroy viruses", "Signal neighboring cells to activate antiviral defenses", "Act as antibodies", "Lyse infected cells"], answer: 1 },
        { q: "Which virus is known to destroy helper T-cells, leading to immunodeficiency?", options: ["Influenza virus", "HIV", "Hepatitis B virus", "Rhinovirus"], answer: 1 },
        { q: "Kaposi's sarcoma in AIDS patients is caused by:", options: ["HIV directly", "Human herpesvirus-8 (HHV-8)", "Cytomegalovirus", "Epstein-Barr virus"], answer: 1 },
        { q: "A cytokine storm is a severe immune reaction often associated with which virus?", options: ["HIV", "Avian influenza virus", "Rhinovirus", "Hepatitis A virus"], answer: 1 },
        { q: "Prion diseases affect which organ system primarily?", options: ["Respiratory system", "Nervous system", "Digestive system", "Circulatory system"], answer: 1 },
        { q: "Viral syncytia formation is a mechanism used by which virus to spread directly between cells?", options: ["Poliovirus", "HIV", "Hepatitis B virus", "Adenovirus"], answer: 1 },
        { q: "Which hepatitis virus is transmitted via the fecal-oral route?", options: ["Hepatitis B", "Hepatitis C", "Hepatitis A", "Hepatitis D"], answer: 2 },
        { q: "The 'window period' in HIV infection refers to the time when:", options: ["The virus is dormant", "Antibodies are not yet detectable", "Symptoms are most severe", "The virus cannot be transmitted"], answer: 1 },
        { q: "Cotton Leaf Curl Virus in Pakistan is transmitted by:", options: ["Mosquitoes", "Whiteflies", "Aphids", "Beetles"], answer: 1 },
        { q: "Which viral disease is characterized by Koplik's spots in the mouth?", options: ["Dengue", "Measles", "Chickenpox", "Rubella"], answer: 1 },
        { q: "Arboviruses are transmitted by:", options: ["Rodents", "Arthropods (e.g., mosquitoes, ticks)", "Contaminated water", "Airborne droplets"], answer: 1 },
        { q: "Ebola virus is primarily transmitted through:", options: ["Airborne droplets", "Direct contact with infected body fluids", "Contaminated food", "Mosquito bites"], answer: 1 },
        { q: "The basic reproduction number (R0) indicates:", options: ["Mortality rate", "Transmission potential", "Incubation period", "Genome size"], answer: 1 },
        { q: "Which hepatitis virus requires co-infection with Hepatitis B virus?", options: ["HAV", "HCV", "HDV", "HEV"], answer: 2 },
        { q: "A pandemic is defined as:", options: ["A disease outbreak in a small community", "A disease spread across a country", "A disease spread across multiple continents", "A disease that affects only animals"], answer: 2 },
        { q: "Which virus has bats as its natural reservoir?", options: ["Influenza virus", "Ebola virus", "Hepatitis C virus", "Rhinovirus"], answer: 1 },
        { q: "Antigenic shift in influenza viruses is a result of:", options: ["Point mutations", "Genome reassortment between different strains", "Reverse transcription", "Integration into host genome"], answer: 1 },
        { q: "The primary vector for Dengue virus is:", options: ["Anopheles mosquito", "Aedes mosquito", "Sandfly", "Tick"], answer: 1 },
        { q: "Vertical transmission refers to:", options: ["Transmission between individuals of the same generation", "Transmission from parent to offspring", "Transmission via vectors", "Airborne transmission"], answer: 1 },
        { q: "Herd immunity occurs when:", options: ["A large percentage of the population is vaccinated or immune", "The virus mutates to a weaker form", "All infected individuals are isolated", "Animals are vaccinated"], answer: 0 },
        { q: "Plaque assays are used to measure:", options: ["Antibody levels", "Viral infectivity (PFU/mL)", "Genome size", "Capsid symmetry"], answer: 1 },
        { q: "The Western blot test is used to:", options: ["Detect viral RNA", "Confirm HIV infection by detecting specific antibodies/antigens", "Measure CD4 count", "Culture viruses"], answer: 1 },
        { q: "Electron microscopy is particularly useful for:", options: ["Diagnosing common colds", "Visualizing novel or unculturable viruses", "Measuring viral load", "Detecting antibodies"], answer: 1 },
        { q: "PCR (Polymerase Chain Reaction) is used to:", options: ["Detect viral proteins", "Amplify and detect viral nucleic acids", "Measure antibody titers", "Culture viruses"], answer: 1 },
        { q: "Hemagglutination inhibition assays detect:", options: ["Viral DNA", "Neutralizing antibodies", "Capsid proteins", "Reverse transcriptase activity"], answer: 1 },
        { q: "The 'window period' in HIV testing can be reduced by using:", options: ["ELISA alone", "PCR for viral RNA", "Western blot", "CD4 count"], answer: 1 },
        { q: "Viral load testing measures:", options: ["Antibody levels", "Number of viral genome copies per mL", "CD4+ T-cell count", "Capsid protein concentration"], answer: 1 },
        { q: "Which diagnostic method is considered gold standard for confirming HIV?", options: ["Rapid test", "ELISA", "Western blot", "Viral culture"], answer: 2 },
        { q: "Inclusion bodies in rabies-infected neurons are called:", options: ["Negri bodies", "Guarnieri bodies", "Lewy bodies", "Pappataci bodies"], answer: 0 },
        { q: "Quantitative PCR (qPCR) is superior for:", options: ["Determining viral morphology", "Measuring exact viral genome copies", "Detecting antibodies", "Culturing viruses"], answer: 1 },
        { q: "AZT (Zidovudine) is an antiretroviral that inhibits:", options: ["HIV protease", "Reverse transcriptase", "Integrase", "Viral entry"], answer: 1 },
        { q: "Neuraminidase inhibitors (e.g., Oseltamivir) are used to treat:", options: ["HIV", "Influenza", "Hepatitis C", "Herpes"], answer: 1 },
        { q: "Protease inhibitors in HIV therapy prevent:", options: ["Viral entry", "Cleavage of viral polyproteins", "Reverse transcription", "Integration"], answer: 1 },
        { q: "Live attenuated vaccines contain:", options: ["Killed pathogens", "Weakened but living pathogens", "Toxoid proteins", "DNA fragments"], answer: 1 },
        { q: "Virus-like particle (VLP) vaccines contain:", options: ["Live virus", "Empty viral capsids without genetic material", "Inactivated virus", "Viral DNA"], answer: 1 },
        { q: "The Oral Polio Vaccine (OPV) contains:", options: ["Killed virus", "Attenuated virus", "Viral DNA", "Capsid proteins only"], answer: 1 },
        { q: "mRNA vaccines (e.g., COVID-19 vaccines) work by:", options: ["Introducing live virus into the body", "Delivering mRNA that encodes viral protein, prompting immune response", "Injecting killed virus", "Providing ready-made antibodies"], answer: 1 },
        { q: "Broad-spectrum antivirals often target:", options: ["Viral capsids", "Host factors essential for viral replication", "Viral envelopes", "Antibody production"], answer: 1 },
        { q: "Phage therapy uses bacteriophages to treat:", options: ["Viral infections", "Bacterial infections", "Fungal infections", "Prion diseases"], answer: 1 },
        { q: "CRISPR-Cas technology is being explored to target:", options: ["Only bacterial infections", "Specific viral genomes", "Host DNA exclusively", "Prion proteins"], answer: 1 },
        { q: "Giant viruses (e.g., Mimivirus) challenge traditional definitions because they:", options: ["Lack DNA", "Encode cellular metabolic genes", "Cannot be seen under light microscopy", "Infect only plants"], answer: 1 },
        { q: "Metagenomics has revolutionized virology by enabling detection of:", options: ["Only known viruses", "Unculturable and novel viruses in environmental samples", "Prions only", "Bacterial pathogens"], answer: 1 },
        { q: "The 'One Health' approach emphasizes the interconnection between:", options: ["Viruses and bacteria only", "Human, animal, and environmental health", "Plants and viruses only", "Vaccines and antivirals"], answer: 1 },
        { q: "Zoonotic spillover refers to:", options: ["Transmission between humans only", "Transmission from animals to humans", "Transmission via vectors only", "Laboratory accidents"], answer: 1 },
        { q: "Viroporins are viral proteins that:", options: ["Form ion channels in host membranes", "Replicate viral genome", "Assemble capsids", "Act as RNA polymerase"], answer: 0 },
        { q: "Defective interfering particles are viral mutants that:", options: ["Enhance viral replication", "Compete with wild-type virus for replication machinery", "Cause immediate lysis", "Act as vaccines"], answer: 1 },
        { q: "The 'quasispecies' concept in virology refers to:", options: ["A single viral strain", "A population of genetically diverse viral variants", "Different virus species in one host", "Viruses that infect multiple hosts"], answer: 1 },
        { q: "Endogenous retroviruses are:", options: ["Always active and causing disease", "Viral sequences integrated into host genome and inherited", "Found only in bacteria", "A type of viroid"], answer: 1 },
        { q: "The Red Queen hypothesis in viral evolution describes:", options: ["Host-parasite coevolutionary arms race", "Viral genome stability", "Vaccine failure", "Viral latency"], answer: 0 },
        { q: "Viral dark matter refers to:", options: ["Well-characterized viruses", "Uncharacterized viral sequences in metagenomic data", "Prions", "Inactive viral particles"], answer: 1 },
        { q: "Oncolytic viruses are engineered to:", options: ["Cause cancer", "Target and kill cancer cells", "Treat bacterial infections", "Act as vaccines"], answer: 1 },
        { q: "CRISPR-Cas systems naturally function in bacteria as:", options: ["Metabolic pathways", "Defense against bacteriophages", "DNA replication machinery", "Protein synthesis systems"], answer: 1 },
        { q: "Phage display technology is used to:", options: ["Treat viral infections", "Evolve and select novel proteins/antibodies", "Sequence viral genomes", "Culture viruses"], answer: 1 },
        { q: "Synthetic virology involves:", options: ["Studying only natural viruses", "Engineering viral genomes for research/therapeutics", "Destroying all viruses", "Creating new viral diseases"], answer: 1 },
        { q: "Organoid models are used in virology to:", options: ["Replace animal models entirely", "Mimic human tissue architecture for infection studies", "Mass-produce viruses", "Develop new vaccines directly"], answer: 1 },
        { q: "Nanopore sequencing allows:", options: ["Only DNA sequencing", "Real-time, long-read sequencing of viral genomes", "Protein structure determination", "Viral culture"], answer: 1 },
        { q: "The 'virosphere' refers to:", options: ["A single virus particle", "The global ecological community of viruses", "Viral capsid structure", "A type of viroid"], answer: 1 },
        { q: "Personalized virology considers:", options: ["Only viral genetics", "Host genetic factors in infection and treatment", "Universal vaccines only", "One-size-fits-all antivirals"], answer: 1 },
        { q: "AI (Artificial Intelligence) is being used in virology to:", options: ["Predict viral-host interactions and protein structures", "Replace all lab work", "Create synthetic viruses only", "Diagnose without tests"], answer: 0 },
        { q: "The future of virology includes understanding:", options: ["Virus-host ecosystems and global viral ecology", "Only viral structure", "How to eliminate all viruses", "Plant viruses exclusively"], answer: 0 }
    ]
}
  ];
